# fly.toml app configuration file generated for capitalpay-decl-bot on 2025-05-04T22:43:58+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'capitalpay-decl-bot'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
